### ISSUE TITLE
Performance of loki::Search with lots of entries

### ISSUE THREAD

**Issue by TeXitoi** [valhalla/baldr#297]
Our 1x192 request use a lot of time in `GraphTile::edgeinfos()` and `EdgeInfos::shape()`. `EdgeInfos::shape()` is cached, but `EdgeInfos` is not cached in `GraphTile`.

As we search 192 points, we basically re-generate `EdgeInfos` for each of these 192 points. Thus, caching `GraphTile::edgeinfos()` might improve drastically the performances in our usecase.

I can cache this info using the technique used in `GraphReader::GetGraphTile()`. Are you OK with that? Do you see any reason why that's a bad idea or it will not work? Do you have any other idea to fix this problem?

Thanks in advance.

**Comment by kevinkreiser** [comment]
ive thought about doing this many times but ive never profiled it because i assumed it to be negligable! if you make this change, can you show us a performance difference with the tools repository application called `valhalla_benchmark_loki`? it would be interesting to see the measured difference! thanks!
